In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.constant([[1, 2, 3, 4, 5]])

In [3]:
y = tf.ones((1,5))

In [4]:
z = tf.zeros((1,5))

In [5]:
q = tf.range(start=1, limit=6, delta=1)

In [6]:
print(x)
print(y)
print(z)
print(q)

tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)
tf.Tensor([[1. 1. 1. 1. 1.]], shape=(1, 5), dtype=float32)
tf.Tensor([[0. 0. 0. 0. 0.]], shape=(1, 5), dtype=float32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

In [7]:
list = [[[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]]]
tensor_3d = tf.constant(list)
print(tensor_3d)

tf.Tensor(
[[[ 0 1 2]
 [ 3 4 5]]

 [[ 6 7 8]
 [ 9 10 11]]], shape=(2, 2, 3), dtype=int32)

In [8]:
tensor_shape = tensor_3d.shape
print("The shape of the 3-D Tensor Object is ", tensor_shape)

The shape of the 3-D Tensor Object is (2, 2, 3)

In [9]:
tensor_size = tf.size(tensor_3d).numpy()
print("The size of the 3-D Tensor Object is ", tensor_size)

The size of the 3-D Tensor Object is 12

In [10]:
tensor_dtype = tensor_3d.dtype
print("The data type selected forthis Tensor Object is ", tensor_dtype)

The data type selected forthis Tensor Object is <dtype: 'int32'>

In [11]:
single_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
tensor_1d = tf.constant(single_list)
print(tensor_1d)

tf.Tensor([ 0 1 2 3 4 5 6 7 8 9 10 11], shape=(12,), dtype=int32)

In [12]:
print("The first element is: ", tensor_1d[0].numpy())

The first element is: 0

In [13]:
print("The last element is: ", tensor_1d[-1].numpy())

The last element is: 11

In [14]:
print("The elements in between the first and the last are:", tensor_1d[1:-1].numpy())

The elements in between the first and the last are: [ 1 2 3 4 5 6 7 8 9 10]

In [15]:
list = [ [0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11] ]
tensor_2d = tf.constant(list)
print(tensor_2d)

tf.Tensor(
[[ 0 1 2 3 4 5]
 [ 6 7 8 9 10 11]], shape=(2, 6), dtype=int32)

In [16]:
print("The first element of the first level is: ", tensor_2d[0].numpy())
print("The second element of the first level is: ", tensor_2d[1].numpy())

The first element of the first level is: [0 1 2 3 4 5]
The second element of the first level is: [ 6 7 8 9 10 11]

In [17]:
print("The second element of the second level is: ", tensor_2d[0, 0].numpy())

The second element of the second level is: 0

In [18]:
print("The third element of the second level is: ", tensor_2d[0, 2].numpy())

The third element of the second level is: 2

In [19]:
tensor1 = tf.constant([[2, 4],[6, 8]], dtype=tf.float32)

tensor2 = tf.constant([[1, 3],[5, 7]], dtype=tf.float32)

print(tensor1)
print(tensor2)

tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [5. 7.]], shape=(2, 2), dtype=float32)

In [20]:
added = tf.add(tensor1, tensor2)
print(added)

tf.Tensor(
[[ 3. 7.]
 [11. 15.]], shape=(2, 2), dtype=float32)

In [21]:
multiply_tensors = tf.multiply(tensor1, tensor2)
print(multiply_tensors)

tf.Tensor(
[[ 2. 12.]
 [30. 56.]], shape=(2, 2), dtype=float32)

In [22]:
matmul_tensors = tf.matmul(tensor1, tensor2)
print(matmul_tensors)

tf.Tensor(
[[22. 34.]
 [46. 74.]], shape=(2, 2), dtype=float32)

In [23]:
print("The maximum value of the tensor1 object is:",  tf.reduce_max(tensor1).numpy())

The maximum value of the tensor1 object is: 8.0

In [24]:
print("The minimum value of the tensor1 object is:",  tf.reduce_min(tensor1).numpy())

The minimum value of the tensor1 object is: 2.0

In [25]:
print("The index position of the maximum element of the tensor1 object is:",
  tf.argmax(tensor1).numpy())

The index position of the maximum element of the tensor1 object is: [1 1]

In [26]:
tensor1 = tf.constant([[1, 2, 3, 4, 5, 6]])
print('The shape of the initial Tensor object is:', tensor1.shape)

The shape of the initial Tensor object is: (1, 6)

In [27]:
tensor2 = tf.reshape(tensor1, [6, 1])
print('The shape of the first reshaped Tensor object is:', tensor2.shape)

The shape of the first reshaped Tensor object is: (6, 1)

In [28]:
tensor3 = tf.reshape(tensor1, [3, 2])
print('The shape of the second reshaped Tensor object is:', tensor3.shape)

The shape of the second reshaped Tensor object is: (3, 2)

In [29]:
print('The shape of the flattened Tensor object is:', tf.reshape(tensor1, [-1]))

The shape of the flattened Tensor object is: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)

In [30]:
list = [[1,2,3], [4,5,], [6]]
ragged_tensor = tf.ragged.constant(list)
print(ragged_tensor)

<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>

In [31]:
string_tensor = tf.constant(["This is", "an String Tensor", "created with TensorFlow"])
print(string_tensor)

tf.Tensor([b'This is' b'an String Tensor' b'created with TensorFlow'], shape=(3,), dtype=string)

In [32]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [2, 2], [4, 4]], 
                                       values=[25, 50, 100], 
                                       dense_shape=[5, 5])


print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[ 25 0 0 0 0]
 [ 0 0 0 0 0]
 [ 0 0 50 0 0]
 [ 0 0 0 0 0]
 [ 0 0 0 0 100]], shape=(5, 5), dtype=int32)